// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3tYHEvco22ipSAnnlquLlZ-_X6trZH34',
    appId: '1:504417196897:web:e6b52aabe76eaa80c50320',
    messagingSenderId: '504417196897',
    projectId: 'notes-sharing-8e0f6',
    authDomain: 'notes-sharing-8e0f6.firebaseapp.com',
    storageBucket: 'notes-sharing-8e0f6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw1DkjK2_r90djjRI-Y3syv5t39VdQO_k',
    appId: '1:504417196897:android:719b5c77f8471384c50320',
    messagingSenderId: '504417196897',
    projectId: 'notes-sharing-8e0f6',
    storageBucket: 'notes-sharing-8e0f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCFOcTFoBV7fYVz2Re9ttDnMPGI24bEzk',
    appId: '1:504417196897:ios:b4836ac8550c4387c50320',
    messagingSenderId: '504417196897',
    projectId: 'notes-sharing-8e0f6',
    storageBucket: 'notes-sharing-8e0f6.firebasestorage.app',
    iosBundleId: 'com.example.noteshareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCFOcTFoBV7fYVz2Re9ttDnMPGI24bEzk',
    appId: '1:504417196897:ios:b4836ac8550c4387c50320',
    messagingSenderId: '504417196897',
    projectId: 'notes-sharing-8e0f6',
    storageBucket: 'notes-sharing-8e0f6.firebasestorage.app',
    iosBundleId: 'com.example.noteshareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3tYHEvco22ipSAnnlquLlZ-_X6trZH34',
    appId: '1:504417196897:web:e72ef9c725915f85c50320',
    messagingSenderId: '504417196897',
    projectId: 'notes-sharing-8e0f6',
    authDomain: 'notes-sharing-8e0f6.firebaseapp.com',
    storageBucket: 'notes-sharing-8e0f6.firebasestorage.app',
  );
}
